services:
  base:
    build:
      context: .
    volumes: &ansible_volumes
      - type: bind
        source: ${PWD}
        target: /var/opt/ansible
        read_only: true
      - type: bind
        source: ~/.ansible
        target: /root/.ansible
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
        read_only: true

  ansible:
    entrypoint: ansible
    build:
      context: .
    volumes: *ansible_volumes

  ansible-playbook:
    entrypoint: ansible-playbook
    build:
      context: .
    volumes: *ansible_volumes
