all:
  hosts:
    local:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      ansible_ssh_user: root
    vm:
      ansible_host: 10.252.6.92
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ansible
